import Head from 'next/head'
import Script from 'next/script'
import "bootstrap/dist/css/bootstrap.min.css"; // Import bootstrap CSS
import Layout from '../app/Layout'
import '../styles/globals.css'
import { useEffect } from 'react';

export default function App({ Component, pageProps }) {

  useEffect(() => {
    require("bootstrap/dist/js/bootstrap.bundle.min.js");
  }, []);

  return (
    <>
    <Head>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
      <link rel="preconnect" href="https://fonts.googleapis.com" />
      <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
    </Head>
    <Layout>
      <Component {...pageProps} />
    </Layout>
    </>
  )
}
